---
# Example of creating /etc/secrets.yaml from a ConfigMap
# which allow for pulling secrets from AWS Secrets Manager
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-secrets
data:
  secrets.yaml: |
    ---
    SPLUNK_HEC_TOKEN: !var /splunk/hec/token
    SPLUNK_PASSWORD: !var /splunk/password
    SPLUNK_IDXC_SECRET: !var /splunk/idxc/secret
    SPLUNK_SHC_SECRET: !var /splunk/shc/secret
    SPLUNK_LICENSE: !var /splunk/license

---
# Setup Service for manging internal networking.
apiVersion: v1
kind: Service
metadata:
  name: splunk-defaults
  labels:
    app: splunk
spec:
  selector:
    name: splunk-defaults
  ports:
    - name: nginx-web
      port: 80
      targetPort: 80
  clusterIP: None

---
# Setup Deployment for serving defaults.yml.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-defaults
  labels:
    app: splunk
spec:
  selector:
    matchLabels:
      name: splunk-defaults
  replicas: 1
  template:
    metadata:
      labels:
        name: splunk-defaults
    spec:
      containers:
      - name: splunk-defaults
        image: jmervine/splunk-nginx-defaults:latest
        ports:
        - containerPort: 80
        env:
        - name: DEBUG
          value: "true"
        - name: SPLUNK_IDXC_ENABLE
          value: "true"
        - name: SPLUNK_SHC_ENABLE
          value: "true"
        volumeMounts:
        - name: etc-secrets
          mountPath: /data/secrets/
      volumes:
      - name: etc-secrets
        configMap:
          name: etc-secrets
